<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Thread extends Model
{
    protected $guarded = [];
    protected $with = ['user'];

    public function getRouteKeyName()
    {
        return 'title'; // TODO: Change the autogenerated stub
    }

    public function path() {
        return "threads/{$this->title}";
    }

    public function user() {
        return $this->belongsTo(User::class);
    }

    public function replies() {
        return $this->hasMany(Reply::class);
    }


    public function addReply($reply) {
       return $this->replies()->create($reply);
    }





}
